### ISSUE TITLE
tutorial for building android

### ISSUE THREAD

**Issue by anhoev** [RockchipOpensourceCommunity/popmetal-kernel-3.14#4]
Hi, can someone write a tutorial for building complete android 5 with kernel 3.14 ?

**Comment by markyzq** [comment]
Actually, this kernel only use for linux stack, not for android.

You can use following kernel for android:
    https://github.com/RockchipOpensourceCommunity/popmetal-android-kernel-3.10

**Comment by anhoev** [comment]
but kernel 3.10 doesn't support drm , i need drm for dual display (LVDS + EDP)

**Comment by markyzq** [comment]
yes, kernel 3.10 not support drm, but rockchip custom define some api, also can support dual screen display. (lcd + hdmi)

Hmmm, (LVDS + EDP) need some hack, How about hack edp as hdmi connector on kernel?

**Comment by anhoev** [comment]
How to do this ?

**Comment by markyzq** [comment]
The drm on kernel 3.14 not support atomic update feature, it's not suitable for android to do windows hardware compose.

BTW, Rockchip support kernel 4.4(drm) + android 7.1,  the drm on kernel 4.4 support atomic feature:
You can found the kernel here:
   https://github.com/rockchip-linux/kernel
But this kernel not develop for android 5

**Comment by markyzq** [comment]
[双lcd屏显示.zip](https://github.com/RockchipOpensourceCommunity/popmetal-kernel-3.14/files/1305663/lcd.zip)

Attachment is dual screen(LVDS + EDP) patches for kernel 3.10, the hwcomposer libs maybe is for android 5, I guess, you can try it.

**Comment by anhoev** [comment]
Did you build android 7.1 successful ? 
I will try with your patch . 
What should i do with the hwcomposer.rk30board.so file ?

**Comment by markyzq** [comment]
Do you have rockchip android 5.1 project?

**Comment by anhoev** [comment]
i use from firefly

**Comment by anhoev** [comment]
i see some errors when i apply your patch

```
 : warning: arch/arm/boot/dts/lcd-F402.dtsi has type 100644, expected 100755
error: patch failed: arch/arm/boot/dts/lcd-F402.dtsi:122
error: arch/arm/boot/dts/lcd-F402.dtsi: patch does not apply
error: patch failed: arch/arm/boot/dts/lcd-b101ew05.dtsi:64
error: arch/arm/boot/dts/lcd-b101ew05.dtsi: patch does not apply
error: patch failed: arch/arm/boot/dts/lcd-box.dtsi:3
error: arch/arm/boot/dts/lcd-box.dtsi: patch does not apply
error: arch/arm/boot/dts/rk3288-box.dts: No such file or directory
warning: arch/arm/boot/dts/rk3288-tb_8846.dts has type 100644, expected 100755
error: patch failed: arch/arm/boot/dts/rk3288-tb_8846.dts:656
error: arch/arm/boot/dts/rk3288-tb_8846.dts: patch does not apply
warning: arch/arm/boot/dts/rk3288.dtsi has type 100755, expected 100644
error: patch failed: drivers/video/rockchip/rk_fb.c:71
error: drivers/video/rockchip/rk_fb.c: patch does not apply
error: patch failed: drivers/video/rockchip/screen/rk_screen.c:4
error: drivers/video/rockchip/screen/rk_screen.c: patch does not apply
warning: drivers/video/rockchip/transmitter/rk32_dp.c has type 100644, expected 100755
error: patch failed: drivers/video/rockchip/transmitter/rk32_dp.c:119
error: drivers/video/rockchip/transmitter/rk32_dp.c: patch does not apply
warning: drivers/video/rockchip/transmitter/rk32_dp.h has type 100644, expected 100755
error: patch failed: drivers/video/rockchip/transmitter/rk32_dp.h:566
error: drivers/video/rockchip/transmitter/rk32_dp.h: patch does not apply
error: patch failed: drivers/video/rockchip/transmitter/rk32_lvds.c:140
error: drivers/video/rockchip/transmitter/rk32_lvds.c: patch does not apply
error: patch failed: include/dt-bindings/rkfb/rk_fb.h:12
error: include/dt-bindings/rkfb/rk_fb.h: patch does not apply
error: patch failed: include/linux/rk_fb.h:786
error: include/linux/rk_fb.h: patch does not apply
warning: include/linux/rk_screen.h has type 100755, expected 100644
error: patch failed: include/linux/rk_screen.h:144
error: include/linux/rk_screen.h: patch does not apply
```

**Comment by anhoev** [comment]
i try to build rom for one POS (RK3288) , that use dual display. My rom works with all devices except 2.display(lvds) .

**Comment by anhoev** [comment]
i am trying to apply the patch manually .

**Comment by anhoev** [comment]
It works !!!
Very nice, thank you very much .

**Comment by anhoev** [comment]
One question more: 
Do you know how to build system.img with root permission ?

**Comment by markyzq** [comment]
Sorry, I don't know, root permission is not recommend, it's dangerous.
